<?php $state = $this->getCurrentState(); ?>
<?php if ($state): ?>
    
    <h1><?php echo $state->getName(); ?></h1>
    <p><a href="<?php echo $this->helper('dan_sca/state')->getStateUrl($state); ?>" title="<?php echo $this->escapeHtml($state->getName()); ?>"><?php echo $state->getName(); ?></a></p>
    <?php echo $state->getDescription(); ?>
    <p><a href="<?php echo $this->getUrl('dan_sca/index/index') ?>" title="<?php echo $this->__('Back to State Directory'); ?>"><?php echo $this->__('&laquo; Back to State Directory'); ?></a></p>
    
<?php endif; ?>