<?php
/**
 * Sportsmans Common App
 *
 * NOTICE OF LICENSE
 *
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
	
	/* Code to Support Changing Display based on Attribute Set (product type) */
	
	// Get attribute set model.
	$model = Mage::getModel('eav/entity_attribute_set');

	// Get attribute set id.
	$attributeSetId = $_product->getAttributeSetId();
	$attributeSet = $model->load($attributeSetId);

	// This is attribute set name.
	$attributeSetName = $attributeSet->getAttributeSetName();
	
	$gameunitOptions = $attributeSetName == 'Draw Entry' ? 1 : 0;
	
	// if the product is a draw entry (has gameunitOptions), then determine if we have the user's state of residence
	if($gameunitOptions){
		$popup = true;
		$customerSession = Mage::getSingleton('customer/session');
		if($stateOfResidence_id = $customerSession->getCustomer()->getStateOfResidence() || $customerSession->getStateOfResidence())
			$popup = false;
	};

?>


<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form" <?php if($gameunitOptions): echo 'enctype="multipart/form-data"'; endif; ?>>
			
			<?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-img-box">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="product-shop">
                <div class="product-name">
                    <span class="h1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                </div>

                <div class="price-info">
                    <?php echo $this->getPriceHtml($_product); ?>
                    <?php echo $this->getChildHtml('bundle_prices') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                </div>

                <div class="extra-info">
                    <?php echo $this->getReviewsSummaryHtml($_product, 'default', false)?>
                    <?php echo $this->getChildHtml('product_type_availability'); ?>
                </div>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>



                <?php echo $this->getChildHtml('other');?>
                
				<?php if ($gameunitOptions):?>
                	<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
				<?php endif; ?>

            </div>

            <div class="add-to-cart-wrapper">
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$gameunitOptions):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
							
							
							<!-- *** enable the Add to Cart button !-->
							<script type="text/javascript">
								var button = document.getElementById("addToCart");
								button.disabled=false;
							</script>
							
							
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php echo $this->getChildHtml('sharing') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php echo $this->getChildHtml('sharing') ?>
                    </div>
                <?php endif; ?>
            </div>

            <?php echo $this->getChildHtml('related_products') ?>

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>

        </script>
    </div>

    <div class="product-collateral toggle-content tabs">
        <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
            <dl id="collateral-tabs" class="collateral-tabs">
                <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                    <dd class="tab-container">
                        <div class="tab-content"><?php echo $html ?></div>
                    </dd>
                <?php endforeach;?>
            </dl>
        <?php endif; ?>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>

<!-- Code to handle State of Residence selector !-->

<?php if($popup): ?>
	<?php $collection = Mage::getModel('dan_sca/state')->getCollection(); ?>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			setTimeout(function(){ 
				jQuery.colorbox({ width:"95%", inline:true, href:"#residence_popup", closeButton: false, overlayClose: false });
			}, 1500);
		});
	</script>

	<div style='display:none'>
		<div id='residence_popup' style='padding:10px; margin:20px; background-color: lightgrey; text-align:center;'> 
			<h2>Select your State of Residence</h2>
			<p>State fees can vary greatly depending on where you live. <br /><br />In order to see the most-accurate fees, please enter your current state of residence</p>
			<form action="<?php echo $this->getUrl('dan_sca/index/updateResidence'); ?>" method="POST" id="residenceForm" name="residenceForm">
				<select name='state_id'>
					<option value='0'>-- Select State --</option>
					<?php foreach($collection as $_c): ?>
						<option value="<?php echo $_c->getId(); ?>"><?php echo $_c->getName(); ?></option>
					<?php endforeach; ?>
				</select>
				<br />
				<br />
				<input id='btn-submitForm' type="submit" style="padding:5px;" value="Submit">
			</form>
		</div>
	</div>
	
	<script>
		(function ($) {
			$("#residenceForm").submit(function(e){
				
				// prep ajax data
		    	var postData = $(this).serializeArray();
		    	var formURL = $(this).attr("action");
				
				// disable submit button to prevent double submits
				$('#btn-submitForm').attr("disabled", "disabled");
				
				// ajax submit
				jQuery.ajax({
					url : formURL,
					type: "POST",
					data : postData,
					success: function(data, textStatus, jqXHR){
		            	$.colorbox.close();
					},
		        	error: function(jqXHR, textStatus, errorThrown){
		            	alert('Something went wrong - please reload this page');     
		        	}
		    	});
				e.preventDefault();
			});
		}(jQuery));
	</script>
<?php endif; ?>