<?php $gameunit = $this->getCurrentGameunit(); ?>
<?php if ($gameunit): ?>
    
    <h1><?php echo $gameunit->getName(); ?></h1>
	
    <?php echo $gameunit->getDescription(); ?>
	<br />
	<br />
	
	<?php $state = $this->helper('dan_sca/state')->getCurrentState(); ?>
	
    <p><a href="<?php echo $this->helper('dan_sca/state')->getStateUrl($state); ?>" title="<?php echo $this->__('Back to ' . $state->getName()); ?>"><?php echo $this->__('&laquo; Back to ' . $state->getName()); ?></a></p>
    
<?php endif; ?>