<?php
/**
 * SPORTSMANS COMMON APP
 *  Custom post-checkout success page:
 *		- collect additional general information on the user
 *		- collect state-specific information on the user
 */
	$order = Mage::getSingleton('customer/session')->getLastOrder();
	$customer = Mage::getModel('customer/customer')->load($order->getCustomerId());
	$_existing = $customer->getColorEyes() ? 'still' : '';
?>
<div class="page-title">
    <h1 id='status'><?php echo $this->__("Success ... but you're not done!") ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h3 id='status-note' class="sub-title" style="color:#B22222;"><?php echo $this->__('Are your details '. $_existing .' accurate?'); ?></h3>
<br />
<h4 id='status-note-extra' class="sub-title" style="color:red; display:none;"></h4>
<br />
<div id='extra-details'>
	<form action="<?php echo $this->getUrl('dan_sca/index/updateDetails'); ?>" method="POST" id="additional_details" name="additional_details">
		<div id='extra-sca-info'>
			<h4>* Information Required by Most States *</h4>
			<ul>
				<?php if(!$customer->getColorEyes()): ?>
					<li>
						<?php 
							$_attr = Mage::getSingleton('eav/config')->getAttribute('customer', 'color_eyes'); 
							$_opts = $_attr->getSource()->getAllOptions();
							$_custVal = $customer->getColorEyes();
						?>
					
						<label for="color_eyes" style='width:80px; text-align:right; margin-right:5px;'>Eye Color</label>
						<select name="color_eyes" style="width:80px;" required>
							<?php foreach($_opts as $_opt): ?>
								<?php $_selText = $_opt['value'] == $_custVal ? 'selected' : ''; ?>
								<option value="<?php echo $_opt['value']; ?>" <?php echo $_selText; ?>><?php echo $_opt['label']; ?></option>
							<?php endforeach; ?>
						</select>
					</li>
				<?php endif; ?>
				<li>
					<?php 
						$_attr = Mage::getSingleton('eav/config')->getAttribute('customer', 'color_hair'); 
						$_opts = $_attr->getSource()->getAllOptions();
						$_custVal = $customer->getColorHair();
					?>
					
					<label for="color_hair" style='width:80px; text-align:right; margin-right:5px;'>Hair Color</label>
					<select name="color_hair" style="width:80px;" required>
						<?php foreach($_opts as $_opt): ?>
							<?php $_selText = $_opt['value'] == $_custVal ? 'selected' : ''; ?>
							<option value="<?php echo $_opt['value']; ?>" <?php echo $_selText; ?>><?php echo $_opt['label']; ?></option>
						<?php endforeach; ?>
					</select>		
				</li>
				<li>
					<?php 
						$_attr = Mage::getSingleton('eav/config')->getAttribute('customer', 'height'); 
						$_opts = $_attr->getSource()->getAllOptions();
						$_custVal = $customer->getHeight();
					?>
					<label for="height" style='width:80px; text-align:right; margin-right:5px;'>Height (in)</label>
					<select name="height" style="width:80px;" required>
						<?php foreach($_opts as $_opt): ?>
							<?php $_selText = $_opt['value'] == $_custVal ? 'selected' : ''; ?>
							<option value="<?php echo $_opt['value']; ?>" <?php echo $_selText; ?>><?php echo $_opt['label']; ?></option>
						<?php endforeach; ?>
					</select>		
				</li>
				<li>
					<label for="weight" style='width:80px; text-align:right; margin-right:5px;'>Weight (lbs)</label>
					<input type="number" name="weight" min="0" style="width:60px; margin-right:20px;" <?php if($_custVal = $customer->getWeight()): echo 'value="'. $_custVal .'"'; endif; ?> placeholder="190" required>
				</li>
				<?php if(!$customer->getGender()): ?>
				<li>
					<label for="gender" style='width:80px; text-align:right; margin-right:5px;'>Gender</label>
					<select name="gender" required>
						<option value="1">Male</option>
						<option value="2">Female</option>
					</select>		
				</li>
				<?php endif; ?>
				<?php if(!$customer->getDob()): ?>
				<li>
					<label for="birthdate" style='width:80px; text-align:right; margin-right:5px;'>Birthdate</label>
					<input type="date" name="birthdate" required>
				</li>
				<?php endif; ?>
			</ul>
		</div>
	
		<div id='extra-state-info'>
		<?php $items = $order->getAllItems(); ?>
		<?php foreach($items as $_item): ?>
			<?php 	$__item = $_item->getProduct()->getId(); 
					$_resource = $_item->getProduct()->getResource();
					$_stateId = $_resource->getAttributeRawValue($__item, 'state_id', Mage::app()->getStore()); 
					$_state = Mage::getModel('dan_sca/state');
					$_state->load($_stateId);
					$_collection = Mage::getModel('dan_sca/state_info')->getCollection();
					$_collection->getSelect()->where('main_table.parent_id = '. $_stateId);
			?>
			<?php if(count($_collection)): ?>
				<br />
				<h4>-- <?php echo $_state->getName(); ?> --</h4>
				<ul>
				<?php foreach($_collection as $_info): ?>
					<?php $_attrCode = $_info->getAttributeCode(); ?>
					<?php $_custVal = $customer->getData($_attrCode); ?>
					<?php $_inputType = $_info->getInputType(); ?>
					<li>
						<label for="<?php echo $_attrCode; ?>" style='width:120px; text-align:right; margin-right:5px;'><?php echo $_info->getName(); ?></label>
						<input type="<?php echo $_inputType; ?>" style="width:150px;" name="<?php echo $_attrCode; ?>" value="<?php echo $_custVal; ?>" <?php echo $_info->getIsRequired() ? required : '' ?>><?php if($_info->getIsRequired()): ?><span style='margin-left:5px; color:red;'>required</span><?php endif; ?>
					</li>
				<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		<?php endforeach; ?>
		</div>
		<br />
		<input type="hidden" name="key" value="<?php echo $customer->getUpdateToken(); ?>">
		<input id='btn-submitForm' class="button" type="submit" value="Submit">
	</form>
	<br />
	<br />
</div>
<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>



<script>
	(function ($) {
		$("#additional_details").submit(function(e){
			
			// prep ajax data
	    	var postData = $(this).serializeArray();
	    	var formURL = $(this).attr("action");
			
			// disable submit button to prevent double submits
			$('#btn-submitForm').attr("disabled", "disabled");
			
			// ajax submit
			jQuery.ajax({
				url : formURL,
				type: "POST",
				data : postData,
				success: function(data, textStatus, jqXHR){
	            	$('#status').text('Thank you!');
					$('#status-note').css('color','#006400').text('Your details have been updated!');
					$('#extra-details').fadeOut(750);
					<?php if(!$customer->getPoaOnFile()): ?>
						$('#status-note-extra').text('We will process your applications once we receive your signed Power of Attorney!').fadeIn(850);
					<?php endif; ?>
				},
	        	error: function(jqXHR, textStatus, errorThrown){
	            	alert('Please check your data');     
	        	}
	    	});
			e.preventDefault();
		});
	}(jQuery));
</script>
